#!/usr/bin/env python3
# Copyright 2026 Lusoris and Claude (Anthropic)
# SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
"""Encoder knob-space Pareto-frontier analysis (ADR-0305 / Research-0077).

Consumes a `comprehensive.jsonl` knob-sweep file (one row per
`(source, codec, rc_mode, preset, quality, knob_combo)` cell) and
emits per-slice Pareto frontiers on `(bitrate_kbps, vmaf_score)` with
`encode_time_ms` as a tiebreaker. The dominance hull is stratified
**per `(source, codec, rc_mode)` slice** rather than collapsed to a
global hull — Research-0063 showed that a global hull collapses the
rate-control flip and produces consensus recipes that regress NVENC
h264/hevc by ~4 VMAF at cq=30 against the bare encoder defaults.

The regression-detection check (``detect_recipe_regressions``) gates
ship-candidate recipes: any recipe that loses VMAF against the bare
encoder default at matched bitrate within the same slice is excluded
from `tools/vmaf-tune/codec_adapters/*` defaults.

Usage::

    python analyze_knob_sweep.py \\
        --jsonl runs/phase_a/full_grid/comprehensive.jsonl \\
        --out-dir reports/

The sweep file lives at ``runs/phase_a/full_grid/comprehensive.jsonl``
on the local host (gitignored — generated by ``hw_encoder_corpus.py``,
~2 GiB, ~3h to produce on a single host). The synthetic 20-row
fixture in ``ai/tests/test_knob_sweep_analysis.py`` exercises every
public function below without requiring the sweep to exist.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping, Sequence

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Tolerance below which two (bitrate, vmaf) points are treated as ties
# for hull-membership purposes. Calibrated against the per-frame VMAF
# noise floor (~0.1 points) and bitrate quantisation in libavformat
# muxers (~1 kbps).
HULL_VMAF_TOL = 1e-6
HULL_BITRATE_TOL = 1e-6

# Stratification keys the analysis groups by. Order is load-bearing:
# CSV / summary filenames are constructed from these in this order.
STRATIFICATION_KEYS = ("source", "codec", "rc_mode")

# Fields a row must carry to be considered well-formed.
REQUIRED_FIELDS = (
    "source",
    "codec",
    "rc_mode",
    "bitrate_kbps",
    "vmaf_score",
    "encode_time_ms",
)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SweepRow:
    """One cell of the knob sweep.

    The schema mirrors `tools/vmaf-tune/` Phase A SCHEMA_VERSION = 2
    (ADR-0301 sample-clip mode + ADR-0297 multi-codec dispatcher), so a
    rows produced by ``hw_encoder_corpus.py`` flow through this script
    unchanged. Unknown extra keys land in ``extras`` for traceability.
    """

    source: str
    codec: str
    rc_mode: str
    bitrate_kbps: float
    vmaf_score: float
    encode_time_ms: float
    preset: str = ""
    quality: str = ""
    knob_combo: str = ""
    is_bare_default: bool = False
    extras: Mapping[str, object] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, raw: Mapping[str, object]) -> "SweepRow":
        """Coerce a JSONL row dict into a SweepRow.

        Raises ``ValueError`` if required fields are missing or
        non-numeric where a number is expected.
        """
        missing = [k for k in REQUIRED_FIELDS if k not in raw]
        if missing:
            raise ValueError(f"row missing required fields: {missing!r}")
        try:
            bitrate = float(raw["bitrate_kbps"])  # type: ignore[arg-type]
            vmaf = float(raw["vmaf_score"])  # type: ignore[arg-type]
            enc_ms = float(raw["encode_time_ms"])  # type: ignore[arg-type]
        except (TypeError, ValueError) as exc:
            raise ValueError(f"row has non-numeric numeric field: {exc}") from exc
        if not math.isfinite(bitrate) or bitrate <= 0:
            raise ValueError(f"non-positive bitrate: {bitrate!r}")
        if not math.isfinite(vmaf):
            raise ValueError(f"non-finite vmaf: {vmaf!r}")
        knob_combo = str(raw.get("knob_combo", ""))
        if not knob_combo and "knob_dict" in raw:
            knob_combo = _stable_knob_repr(raw["knob_dict"])
        extras = {
            k: v
            for k, v in raw.items()
            if k
            not in {
                *REQUIRED_FIELDS,
                "preset",
                "quality",
                "knob_combo",
                "knob_dict",
                "is_bare_default",
            }
        }
        return cls(
            source=str(raw["source"]),
            codec=str(raw["codec"]),
            rc_mode=str(raw["rc_mode"]),
            bitrate_kbps=bitrate,
            vmaf_score=vmaf,
            encode_time_ms=enc_ms,
            preset=str(raw.get("preset", "")),
            quality=str(raw.get("quality", "")),
            knob_combo=knob_combo,
            is_bare_default=bool(raw.get("is_bare_default", False)),
            extras=extras,
        )


def _stable_knob_repr(knob_dict: object) -> str:
    """Render a knob dict as a stable comma-separated `k=v` string.

    Ordering is alphabetical by key so the same knob set produces the
    same ``knob_combo`` string regardless of dict iteration order in
    the producer.
    """
    if not isinstance(knob_dict, Mapping):
        return ""
    return ",".join(f"{k}={knob_dict[k]}" for k in sorted(knob_dict))


# ---------------------------------------------------------------------------
# IO
# ---------------------------------------------------------------------------


def load_jsonl(path: Path) -> list[SweepRow]:
    """Read a JSONL file into a list of ``SweepRow``.

    Skips blank lines. Re-raises with the offending line number on
    parse failure so the user can identify the bad row.
    """
    rows: list[SweepRow] = []
    with path.open("r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                raw = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{lineno}: invalid JSON: {exc}") from exc
            try:
                rows.append(SweepRow.from_dict(raw))
            except ValueError as exc:
                raise ValueError(f"{path}:{lineno}: {exc}") from exc
    return rows


# ---------------------------------------------------------------------------
# Stratification
# ---------------------------------------------------------------------------


def stratify(rows: Iterable[SweepRow]) -> dict[tuple[str, str, str], list[SweepRow]]:
    """Group rows by ``(source, codec, rc_mode)``.

    The order of keys in each tuple matches ``STRATIFICATION_KEYS`` and
    is load-bearing — downstream filename construction depends on it.
    """
    grouped: dict[tuple[str, str, str], list[SweepRow]] = defaultdict(list)
    for row in rows:
        key = (row.source, row.codec, row.rc_mode)
        grouped[key].append(row)
    return dict(grouped)


# ---------------------------------------------------------------------------
# Pareto hull
# ---------------------------------------------------------------------------


def pareto_frontier(rows: Sequence[SweepRow]) -> list[SweepRow]:
    """Return the Pareto-optimal subset of ``rows``.

    Optimisation directions:

    * minimise ``bitrate_kbps``
    * maximise ``vmaf_score``
    * tiebreaker: minimise ``encode_time_ms`` when bitrate and vmaf
      tie within tolerance.

    Algorithm: sort ascending by bitrate (then descending by vmaf,
    then ascending by encode_time_ms for stable tiebreaking), then
    sweep the running-max vmaf. A row is on the hull iff its vmaf
    strictly exceeds every preceding row's vmaf, OR ties the running
    max but has a strictly lower encode_time_ms among tied points.
    """
    if not rows:
        return []
    ordered = sorted(
        rows,
        key=lambda r: (r.bitrate_kbps, -r.vmaf_score, r.encode_time_ms),
    )
    hull: list[SweepRow] = []
    best_vmaf = -math.inf
    for row in ordered:
        if row.vmaf_score > best_vmaf + HULL_VMAF_TOL:
            hull.append(row)
            best_vmaf = row.vmaf_score
            continue
        # Tie within tolerance: replace previous hull tail iff this
        # row has lower encode time at effectively the same bitrate.
        if hull and abs(row.vmaf_score - best_vmaf) <= HULL_VMAF_TOL:
            tail = hull[-1]
            same_bitrate = abs(tail.bitrate_kbps - row.bitrate_kbps) <= HULL_BITRATE_TOL
            if same_bitrate and row.encode_time_ms < tail.encode_time_ms:
                hull[-1] = row
    return hull


# ---------------------------------------------------------------------------
# Regression detection
# ---------------------------------------------------------------------------


def detect_recipe_regressions(
    rows: Sequence[SweepRow],
    *,
    bitrate_tol_pct: float = 5.0,
    vmaf_tol: float = 0.1,
) -> list[dict[str, object]]:
    """Flag recipes that regress vs the bare encoder default.

    Within each ``(source, codec, rc_mode)`` slice, walk every
    non-bare recipe row and compare its VMAF against the closest bare
    default at matched bitrate (within ``bitrate_tol_pct`` percent).
    Anything more than ``vmaf_tol`` points below the bare baseline is
    a regression and is yielded as a dict with the slice key, the
    knob combination, the matched bare reference, and the
    ``vmaf_delta`` (negative = regression).

    This is the gate that blocks ship-candidate recipes from landing
    as `tools/vmaf-tune/codec_adapters/*` defaults (ADR-0305 + the
    knob-sweep corpus invariant in ``ai/AGENTS.md``).
    """
    regressions: list[dict[str, object]] = []
    for key, slice_rows in stratify(rows).items():
        bare = [r for r in slice_rows if r.is_bare_default]
        if not bare:
            continue
        for cand in slice_rows:
            if cand.is_bare_default:
                continue
            ref = _closest_bare_at_bitrate(cand, bare, bitrate_tol_pct)
            if ref is None:
                continue
            delta = cand.vmaf_score - ref.vmaf_score
            if delta < -vmaf_tol:
                regressions.append(
                    {
                        "source": key[0],
                        "codec": key[1],
                        "rc_mode": key[2],
                        "candidate_knob_combo": cand.knob_combo,
                        "candidate_vmaf": cand.vmaf_score,
                        "candidate_bitrate_kbps": cand.bitrate_kbps,
                        "bare_vmaf": ref.vmaf_score,
                        "bare_bitrate_kbps": ref.bitrate_kbps,
                        "vmaf_delta": delta,
                    }
                )
    return regressions


def _closest_bare_at_bitrate(
    candidate: SweepRow,
    bare_rows: Sequence[SweepRow],
    bitrate_tol_pct: float,
) -> SweepRow | None:
    """Return the bare-default row whose bitrate is closest to ``candidate``.

    Returns ``None`` when no bare default is within
    ``bitrate_tol_pct`` percent of the candidate's bitrate (i.e. the
    operating point isn't comparable, so the regression check abstains
    rather than reports a false positive).
    """
    if not bare_rows:
        return None
    tol = candidate.bitrate_kbps * (bitrate_tol_pct / 100.0)
    best: SweepRow | None = None
    best_gap = math.inf
    for ref in bare_rows:
        gap = abs(ref.bitrate_kbps - candidate.bitrate_kbps)
        if gap <= tol and gap < best_gap:
            best = ref
            best_gap = gap
    return best


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def write_slice_csv(
    out_dir: Path,
    key: tuple[str, str, str],
    hull: Sequence[SweepRow],
) -> Path:
    """Write a single-slice Pareto hull as CSV.

    Filename pattern: ``pareto_<source>_<codec>_<rc_mode>.csv`` —
    matches the pattern documented in ``Research-0077 §Method``.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"pareto_{_slug(key[0])}_{_slug(key[1])}_{_slug(key[2])}.csv"
    path = out_dir / filename
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(
            [
                "source",
                "codec",
                "rc_mode",
                "preset",
                "quality",
                "knob_combo",
                "bitrate_kbps",
                "vmaf_score",
                "encode_time_ms",
                "is_bare_default",
            ]
        )
        for row in hull:
            writer.writerow(
                [
                    row.source,
                    row.codec,
                    row.rc_mode,
                    row.preset,
                    row.quality,
                    row.knob_combo,
                    f"{row.bitrate_kbps:.3f}",
                    f"{row.vmaf_score:.6f}",
                    f"{row.encode_time_ms:.3f}",
                    row.is_bare_default,
                ]
            )
    return path


def write_summary_md(
    out_dir: Path,
    hulls: Mapping[tuple[str, str, str], Sequence[SweepRow]],
    regressions: Sequence[Mapping[str, object]],
) -> Path:
    """Aggregate per-slice hulls into a single markdown summary.

    The summary is the load-bearing reading surface called out by
    ADR-0305 §Consequences ("the per-slice CSV tables are voluminous
    and the markdown summary is the load-bearing reading surface").
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "summary.md"
    lines: list[str] = []
    lines.append("# Encoder knob-space Pareto frontiers — summary")
    lines.append("")
    lines.append(
        "Generated by `ai/scripts/analyze_knob_sweep.py` from the "
        "12,636-cell knob sweep at "
        "`runs/phase_a/full_grid/comprehensive.jsonl`. See "
        "[ADR-0305](../docs/adr/0305-encoder-knob-space-pareto-analysis.md) "
        "and [Research-0077](../docs/research/0077-encoder-knob-space-pareto-frontiers.md)."
    )
    lines.append("")
    lines.append(f"Realised slices: **{len(hulls)}**")
    lines.append("")
    lines.append("## Per-slice hull sizes")
    lines.append("")
    lines.append("| source | codec | rc_mode | hull size |")
    lines.append("|--------|-------|---------|----------:|")
    for key in sorted(hulls):
        lines.append(f"| {key[0]} | {key[1]} | {key[2]} | {len(hulls[key])} |")
    lines.append("")
    lines.append("## Recipe regressions vs bare encoder defaults")
    lines.append("")
    if not regressions:
        lines.append(
            "No regressions detected at the configured tolerance — every "
            "non-bare recipe at matched bitrate either matched or beat "
            "the bare default."
        )
    else:
        lines.append(
            "The following recipes regress against the bare encoder "
            "default at matched bitrate within their slice and **must "
            "not ship** as `tools/vmaf-tune/codec_adapters/*` defaults "
            "(ADR-0305 / `ai/AGENTS.md` knob-sweep corpus invariant):"
        )
        lines.append("")
        lines.append(
            "| source | codec | rc_mode | knob_combo | " "cand vmaf | bare vmaf | Δ vmaf |"
        )
        lines.append("|--------|-------|---------|-----------|" "----------:|----------:|-------:|")
        for reg in regressions:
            lines.append(
                "| {source} | {codec} | {rc_mode} | "
                "`{candidate_knob_combo}` | {cand:.2f} | "
                "{bare:.2f} | {delta:+.2f} |".format(
                    source=reg["source"],
                    codec=reg["codec"],
                    rc_mode=reg["rc_mode"],
                    candidate_knob_combo=reg["candidate_knob_combo"],
                    cand=float(reg["candidate_vmaf"]),
                    bare=float(reg["bare_vmaf"]),
                    delta=float(reg["vmaf_delta"]),
                )
            )
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _slug(text: str) -> str:
    """Filename-safe slug of an arbitrary slice-key component."""
    safe = []
    for ch in text:
        if ch.isalnum() or ch in {"-", "_"}:
            safe.append(ch)
        else:
            safe.append("_")
    return "".join(safe) or "unknown"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def analyze(jsonl_path: Path, out_dir: Path) -> dict[str, object]:
    """End-to-end entry point. Returns a small report dict for tests."""
    rows = load_jsonl(jsonl_path)
    grouped = stratify(rows)
    hulls = {key: pareto_frontier(slice_rows) for key, slice_rows in grouped.items()}
    regressions = detect_recipe_regressions(rows)
    csv_paths = [write_slice_csv(out_dir, key, hull) for key, hull in hulls.items()]
    summary_path = write_summary_md(out_dir, hulls, regressions)
    return {
        "n_rows": len(rows),
        "n_slices": len(hulls),
        "n_regressions": len(regressions),
        "csv_paths": csv_paths,
        "summary_path": summary_path,
    }


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=("Encoder knob-space Pareto-frontier analysis " "(ADR-0305 / Research-0077)."),
    )
    parser.add_argument(
        "--jsonl",
        type=Path,
        required=True,
        help="Path to comprehensive.jsonl knob-sweep file.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="Directory to write per-slice CSVs and summary.md into.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(list(sys.argv[1:] if argv is None else argv))
    if not args.jsonl.exists():
        print(f"error: jsonl not found: {args.jsonl}", file=sys.stderr)
        return 2
    report = analyze(args.jsonl, args.out_dir)
    print(
        f"Analysed {report['n_rows']} rows across {report['n_slices']} "
        f"slices; {report['n_regressions']} recipe regression(s) flagged. "
        f"Summary: {report['summary_path']}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
