#!/usr/bin/env python3
# Copyright 2026 Lusoris and Claude (Anthropic)
# SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
"""Generate the deterministic bisect-model-quality fixture cache.

The fixture is a small synthetic placeholder for a future DMOS-aligned
golden cache (see [Research-0001](../../docs/research/0001-bisect-model-quality-cache.md)).
What lives in `ai/testdata/bisect/` is fully reproducible from this
script with fixed seeds; CI re-runs and asserts byte-equality before
running the bisect, which is how we catch silent drift in pandas /
pyarrow / onnx serialisation.

Layout:

    ai/testdata/bisect/
        features.parquet      256 rows x (6 DEFAULT_FEATURES + mos)
        models/model_NN.onnx  8 linear FR models, all "good"

The committed timeline is intentionally regression-free: the head and
tail both pass the gate, so a green nightly means the bisect end-to-end
wiring still works. The synthetic-regression case lives in
`ai/tests/test_bisect_model_quality.py::test_bisect_localises_first_bad`,
which builds a bad-from-index-5 timeline at runtime.

Usage:

    python ai/scripts/build_bisect_cache.py             # regenerate in place
    python ai/scripts/build_bisect_cache.py --check     # diff against committed
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import onnx
import pandas as pd
from onnx import TensorProto, helper

DEFAULT_FEATURES = (
    "adm2",
    "vif_scale0",
    "vif_scale1",
    "vif_scale2",
    "vif_scale3",
    "motion2",
)
N_FEATURES = len(DEFAULT_FEATURES)
N_ROWS = 256
N_MODELS = 8
FEATURE_SEED = 20260418
MODEL_SEED = 20260419


def _save_linear_fr(path: Path, weights: np.ndarray, bias: float = 0.0) -> None:
    x = helper.make_tensor_value_info("input", TensorProto.FLOAT, ["N", N_FEATURES])
    y = helper.make_tensor_value_info("score", TensorProto.FLOAT, ["N"])
    w = helper.make_tensor(
        "W",
        TensorProto.FLOAT,
        [N_FEATURES, 1],
        weights.astype(np.float32).flatten().tolist(),
    )
    b = helper.make_tensor("b", TensorProto.FLOAT, [1], [float(bias)])
    axes = helper.make_tensor("axes", TensorProto.INT64, [1], [1])
    mm = helper.make_node("MatMul", ["input", "W"], ["mm"])
    add = helper.make_node("Add", ["mm", "b"], ["wide"])
    sq = helper.make_node("Squeeze", ["wide", "axes"], ["score"])
    graph = helper.make_graph([mm, add, sq], "fr_linear", [x], [y], [w, b, axes])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 17)])
    # Pin producer fields so the serialised bytes don't depend on host onnx version.
    model.producer_name = "vmaf-train.bisect-cache"
    model.producer_version = "1"
    model.ir_version = 9
    onnx.save(model, str(path))


def build_features(out: Path) -> None:
    rng = np.random.default_rng(FEATURE_SEED)
    feats = rng.uniform(0.2, 0.9, size=(N_ROWS, N_FEATURES)).astype(np.float32)
    # Targets on the [0, 1] band so a sum-of-features predictor correlates
    # ~ perfectly. Add tiny noise so PLCC is < 1 but well above any sane gate.
    target = feats.sum(axis=1) / N_FEATURES
    target += rng.normal(0.0, 1e-3, size=N_ROWS).astype(np.float32)
    df = pd.DataFrame({name: feats[:, i] for i, name in enumerate(DEFAULT_FEATURES)})
    df["mos"] = target.astype(np.float32)
    # Pin the row index so parquet metadata is reproducible.
    df.index = pd.RangeIndex(start=0, stop=N_ROWS, name="row")
    df.to_parquet(out, engine="pyarrow", compression="zstd", index=True)


def build_models(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(MODEL_SEED)
    good_w = np.full(N_FEATURES, 1.0 / N_FEATURES, dtype=np.float32)
    for i in range(N_MODELS):
        # All models are "good" — tiny perturbations stay well above the
        # PLCC gate. Bisect verdict on this set is "no regression in range".
        w = good_w + rng.normal(0.0, 1e-4, size=N_FEATURES).astype(np.float32)
        _save_linear_fr(out_dir / f"model_{i:02d}.onnx", w)


def regenerate(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    build_features(out_dir / "features.parquet")
    build_models(out_dir / "models")


def check(out_dir: Path) -> int:
    """Return 0 if regenerated bytes match the committed tree."""
    assert out_dir.is_dir(), f"expected committed cache at {out_dir}"
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        regenerate(tmp)
        diffs: list[str] = []
        for committed in sorted(out_dir.rglob("*")):
            if committed.is_dir():
                continue
            if committed.name == "README.md":
                continue
            rel = committed.relative_to(out_dir)
            fresh = tmp / rel
            if not fresh.exists():
                diffs.append(f"missing in regen: {rel}")
                continue
            if not filecmp.cmp(committed, fresh, shallow=False):
                diffs.append(f"byte drift: {rel}")
        for fresh in sorted(tmp.rglob("*")):
            if fresh.is_dir():
                continue
            rel = fresh.relative_to(tmp)
            if not (out_dir / rel).exists():
                diffs.append(f"new file in regen: {rel}")
        if diffs:
            for d in diffs:
                print(f"DRIFT  {d}", file=sys.stderr)
            print(
                "\nRegenerate the committed cache:\n"
                "  python ai/scripts/build_bisect_cache.py\n",
                file=sys.stderr,
            )
            return 1
    print("OK  bisect cache matches regenerated bytes")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "testdata" / "bisect",
        help="Output directory (default: ai/testdata/bisect)",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="Diff regenerated bytes against committed; exit 1 on drift",
    )
    args = p.parse_args()
    if args.check:
        return check(args.out)
    if args.out.exists():
        shutil.rmtree(args.out)
    regenerate(args.out)
    print(f"OK  wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
