/**
 *  Copyright 2026 Lusoris and Claude (Anthropic)
 *  SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
 *
 *  Stub kernel for motion on the vulkan backend. Generated by
 *  /add-gpu-backend — replace with a real implementation.
 */

#include <errno.h>

#include "../../vulkan/common.h"

int vmaf_vulkan_motion_init(VmafVulkanContext *ctx)
{
    (void)ctx;
    /* TODO: allocate device-side scratch buffers */
    return 0;
}

int vmaf_vulkan_motion_run(VmafVulkanContext *ctx, const void *ref, const void *dis, int width,
                           int height, int stride)
{
    (void)ctx;
    (void)ref;
    (void)dis;
    (void)width;
    (void)height;
    (void)stride;
    /* TODO: launch motion kernel on vulkan */
    return -ENOSYS;
}

void vmaf_vulkan_motion_destroy(VmafVulkanContext *ctx)
{
    (void)ctx;
    /* TODO: free device-side scratch buffers */
}
