/**
 *  Copyright 2026 Lusoris and Claude (Anthropic)
 *  SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
 *
 *  VIF feature kernel on the Vulkan backend (T5-1b pathfinder).
 *
 *  THIS PR ships the dispatch plumbing — descriptor sets, pipeline
 *  cache, command-buffer record/submit/wait — using a placeholder
 *  shader (separable horizontal Gaussian blur + reduction sum).
 *  The actual VIF arithmetic (4-scale Gaussian pyramid, per-scale
 *  numerator / denominator, scale ratios) ports kernel-by-kernel
 *  in T5-1b-iv-vif-math follow-up PRs against this same dispatch
 *  scaffolding. This split keeps the runtime PR reviewable and
 *  the kernel-correctness PR small enough to gate on
 *  `/cross-backend-diff` ULP measurements.
 */

#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "../../vulkan/common.h"
#include "../../vulkan/picture_vulkan.h"
#include "../../vulkan/vulkan_internal.h"

/* Generated by libvmaf/src/vulkan/meson.build glslc step:
 *   <build>/.../vif_spv.h declares
 *     static const unsigned int vif_spv[];
 *     static const unsigned int vif_spv_size;
 */
#include "vif_spv.h"

typedef struct {
    VkShaderModule shader;
    VkDescriptorSetLayout dsl;
    VkPipelineLayout pipeline_layout;
    VkPipeline pipeline;
    VkDescriptorPool desc_pool;
    int initialised;
} VifVkState;

/* One state per context — keep it as a TU-local singleton for this
 * pathfinder commit; the production registration plumbing
 * (VmafFeatureExtractor table + per-instance state struct) lands
 * with the kernel-correctness PR. */
static VifVkState g_state = {0};

typedef struct {
    uint32_t width;
    uint32_t height;
    uint32_t stride_uints;
} PushConsts;

int vmaf_vulkan_vif_init(VmafVulkanContext *ctx)
{
    if (!ctx)
        return -EINVAL;
    if (g_state.initialised)
        return 0;

    VkShaderModuleCreateInfo smci = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = vif_spv_size,
        .pCode = vif_spv,
    };
    VkResult vkr = vkCreateShaderModule(ctx->device, &smci, NULL, &g_state.shader);
    if (vkr != VK_SUCCESS)
        return -ENOMEM;

    VkDescriptorSetLayoutBinding bindings[2] = {
        {
            .binding = 0,
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        },
        {
            .binding = 1,
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        },
    };
    VkDescriptorSetLayoutCreateInfo dslci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 2,
        .pBindings = bindings,
    };
    vkr = vkCreateDescriptorSetLayout(ctx->device, &dslci, NULL, &g_state.dsl);
    if (vkr != VK_SUCCESS)
        goto fail_shader;

    VkPushConstantRange pcr = {
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        .offset = 0,
        .size = sizeof(PushConsts),
    };
    VkPipelineLayoutCreateInfo plci = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts = &g_state.dsl,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &pcr,
    };
    vkr = vkCreatePipelineLayout(ctx->device, &plci, NULL, &g_state.pipeline_layout);
    if (vkr != VK_SUCCESS)
        goto fail_dsl;

    VkComputePipelineCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage =
            {
                .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                .stage = VK_SHADER_STAGE_COMPUTE_BIT,
                .module = g_state.shader,
                .pName = "main",
            },
        .layout = g_state.pipeline_layout,
    };
    vkr = vkCreateComputePipelines(ctx->device, VK_NULL_HANDLE, 1, &cpci, NULL, &g_state.pipeline);
    if (vkr != VK_SUCCESS)
        goto fail_pl;

    VkDescriptorPoolSize pool_size = {
        .type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        .descriptorCount = 16, /* room for ~8 dispatches in flight */
    };
    VkDescriptorPoolCreateInfo dpci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT,
        .maxSets = 8,
        .poolSizeCount = 1,
        .pPoolSizes = &pool_size,
    };
    vkr = vkCreateDescriptorPool(ctx->device, &dpci, NULL, &g_state.desc_pool);
    if (vkr != VK_SUCCESS)
        goto fail_pipeline;

    g_state.initialised = 1;
    return 0;

fail_pipeline:
    vkDestroyPipeline(ctx->device, g_state.pipeline, NULL);
fail_pl:
    vkDestroyPipelineLayout(ctx->device, g_state.pipeline_layout, NULL);
fail_dsl:
    vkDestroyDescriptorSetLayout(ctx->device, g_state.dsl, NULL);
fail_shader:
    vkDestroyShaderModule(ctx->device, g_state.shader, NULL);
    memset(&g_state, 0, sizeof(g_state));
    return -ENOMEM;
}

int vmaf_vulkan_vif_run(VmafVulkanContext *ctx, const void *ref, const void *dis, int width,
                        int height, int stride)
{
    if (!ctx || !ref)
        return -EINVAL;
    (void)dis; /* placeholder pathfinder uses ref only */
    if (width <= 0 || height <= 0 || stride <= 0)
        return -EINVAL;
    if (!g_state.initialised) {
        int err = vmaf_vulkan_vif_init(ctx);
        if (err)
            return err;
    }

    /* 4-byte-pack the input row stride: shader reads 4 pixels per
     * uint32 word, so stride must be a multiple of 4. */
    size_t stride_uints = ((size_t)stride + 3u) / 4u;
    size_t input_bytes = stride_uints * sizeof(uint32_t) * (size_t)height;

    VmafVulkanBuffer *in_buf = NULL;
    VmafVulkanBuffer *out_buf = NULL;
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    VkFence fence = VK_NULL_HANDLE;
    VkDescriptorSet desc_set = VK_NULL_HANDLE;
    int err = 0;

    /* Output buffer holds one float per workgroup. Workgroup is
     * 32x8 — round up to cover the plane. */
    uint32_t gx = ((uint32_t)width + 31u) / 32u;
    uint32_t gy = ((uint32_t)height + 7u) / 8u;
    size_t wg_count = (size_t)gx * (size_t)gy;
    size_t output_bytes = wg_count * sizeof(float);

    err = vmaf_vulkan_buffer_alloc(ctx, &in_buf, input_bytes);
    if (err)
        return err;
    err = vmaf_vulkan_buffer_alloc(ctx, &out_buf, output_bytes);
    if (err)
        goto cleanup;

    /* Upload reference plane row-by-row to handle stride padding. */
    {
        uint8_t *dst = (uint8_t *)vmaf_vulkan_buffer_host(in_buf);
        const uint8_t *src = (const uint8_t *)ref;
        size_t row_bytes_dst = stride_uints * sizeof(uint32_t);
        for (int y = 0; y < height; y++) {
            memcpy(dst + (size_t)y * row_bytes_dst, src + (size_t)y * stride, (size_t)width);
        }
    }
    /* Zero the output workgroup-sum slots. */
    memset(vmaf_vulkan_buffer_host(out_buf), 0, output_bytes);
    err = vmaf_vulkan_buffer_flush(ctx, in_buf);
    if (err)
        goto cleanup;
    err = vmaf_vulkan_buffer_flush(ctx, out_buf);
    if (err)
        goto cleanup;

    /* Allocate descriptor set + write bindings. */
    VkDescriptorSetAllocateInfo dsai = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool = g_state.desc_pool,
        .descriptorSetCount = 1,
        .pSetLayouts = &g_state.dsl,
    };
    if (vkAllocateDescriptorSets(ctx->device, &dsai, &desc_set) != VK_SUCCESS) {
        err = -ENOMEM;
        goto cleanup;
    }
    VkDescriptorBufferInfo dbi[2] = {
        {.buffer = (VkBuffer)vmaf_vulkan_buffer_vkhandle(in_buf),
         .offset = 0,
         .range = VK_WHOLE_SIZE},
        {.buffer = (VkBuffer)vmaf_vulkan_buffer_vkhandle(out_buf),
         .offset = 0,
         .range = VK_WHOLE_SIZE},
    };
    VkWriteDescriptorSet writes[2] = {
        {.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
         .dstSet = desc_set,
         .dstBinding = 0,
         .descriptorCount = 1,
         .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .pBufferInfo = &dbi[0]},
        {.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
         .dstSet = desc_set,
         .dstBinding = 1,
         .descriptorCount = 1,
         .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .pBufferInfo = &dbi[1]},
    };
    vkUpdateDescriptorSets(ctx->device, 2, writes, 0, NULL);

    /* Command buffer record. */
    VkCommandBufferAllocateInfo cbai = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = ctx->command_pool,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1,
    };
    if (vkAllocateCommandBuffers(ctx->device, &cbai, &cmd) != VK_SUCCESS) {
        err = -ENOMEM;
        goto cleanup;
    }
    VkCommandBufferBeginInfo cbbi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
    };
    vkBeginCommandBuffer(cmd, &cbbi);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, g_state.pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, g_state.pipeline_layout, 0, 1,
                            &desc_set, 0, NULL);
    PushConsts pc = {
        .width = (uint32_t)width,
        .height = (uint32_t)height,
        .stride_uints = (uint32_t)stride_uints,
    };
    vkCmdPushConstants(cmd, g_state.pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc),
                       &pc);
    vkCmdDispatch(cmd, gx, gy, 1);
    vkEndCommandBuffer(cmd);

    /* Submit + wait. */
    VkFenceCreateInfo fci = {.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    if (vkCreateFence(ctx->device, &fci, NULL, &fence) != VK_SUCCESS) {
        err = -ENOMEM;
        goto cleanup;
    }
    VkSubmitInfo si = {
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .commandBufferCount = 1,
        .pCommandBuffers = &cmd,
    };
    if (vkQueueSubmit(ctx->queue, 1, &si, fence) != VK_SUCCESS) {
        err = -EIO;
        goto cleanup;
    }
    vkWaitForFences(ctx->device, 1, &fence, VK_TRUE, UINT64_MAX);

    /* Pathfinder check: the output buffer holds the reduced sum of
     * blurred pixel values. We don't surface it as a per-feature
     * score yet (kernel-correctness PR does that); this just
     * verifies the dispatch round-trip works. */

cleanup:
    if (fence != VK_NULL_HANDLE)
        vkDestroyFence(ctx->device, fence, NULL);
    if (cmd != VK_NULL_HANDLE)
        vkFreeCommandBuffers(ctx->device, ctx->command_pool, 1, &cmd);
    if (desc_set != VK_NULL_HANDLE)
        vkFreeDescriptorSets(ctx->device, g_state.desc_pool, 1, &desc_set);
    if (out_buf)
        vmaf_vulkan_buffer_free(ctx, out_buf);
    if (in_buf)
        vmaf_vulkan_buffer_free(ctx, in_buf);
    return err;
}

void vmaf_vulkan_vif_destroy(VmafVulkanContext *ctx)
{
    if (!ctx || !g_state.initialised)
        return;
    vkDestroyDescriptorPool(ctx->device, g_state.desc_pool, NULL);
    vkDestroyPipeline(ctx->device, g_state.pipeline, NULL);
    vkDestroyPipelineLayout(ctx->device, g_state.pipeline_layout, NULL);
    vkDestroyDescriptorSetLayout(ctx->device, g_state.dsl, NULL);
    vkDestroyShaderModule(ctx->device, g_state.shader, NULL);
    memset(&g_state, 0, sizeof(g_state));
}
