# Copyright 2026 Lusoris and Claude (Anthropic)
# SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
"""Per-shot VMAF predictor — the predict-then-verify path.

A movie split into shots can be encoded at the right CRF for each shot
*without running VMAF on every shot* by using a learned predictor that
estimates VMAF from cheap signals. This module ships the runtime side
of that loop:

* :class:`ShotFeatures` — the feature vector the predictor consumes
  (probe-encode bitrate, frame-size statistics, optional saliency mean,
  motion energy, shot length, fps, resolution class, codec one-hot).
* :class:`Predictor` — loads an ONNX model when available; falls back
  to a per-codec analytical curve so unit tests run without
  onnxruntime and so the harness degrades gracefully on hosts without
  the ML stack.
* :func:`pick_crf` — inverts the predictor by binary search over the
  codec's ``quality_range`` to find the CRF that hits a target VMAF.
* :func:`pick_keyint` — heuristic GOP picker driven by probe bitrate +
  shot length, returning ``(keyint, min_keyint)`` for the codec
  adapter's ``gop_args``.
* :func:`make_predictor_predicate` — adapts a :class:`Predictor` to the
  ``PredicateFn`` signature consumed by
  :func:`vmaftune.per_shot.tune_per_shot`.

The predictor is the predict half of the predict-then-verify loop;
:mod:`vmaftune.predictor_validate` is the verify half.

The shipped model files (``model/predictor_<codec>.onnx``) train
offline via :mod:`vmaftune.predictor_train` from a corpus generated by
:mod:`vmaftune.corpus`. The trained coefficients are versioned alongside
the model card under ``model/`` per ADR.
"""

from __future__ import annotations

import dataclasses
import math
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import TYPE_CHECKING

from .codec_adapters import get_adapter

if TYPE_CHECKING:
    from .per_shot import Shot

# ``PredicateFn`` mirror — re-imported through :mod:`vmaftune.per_shot`
# at call sites. Reproduced here to avoid an import cycle.
PredicateFn = Callable[["Shot", float, str], tuple[int, float]]


@dataclasses.dataclass(frozen=True)
class ShotFeatures:
    """Cheap-to-compute signals per shot fed to the VMAF predictor.

    Shape rationale: every entry is either trivially extractable from
    the probe encode's stderr or one ONNX forward pass on a single
    centre frame. No entry requires running VMAF or the final encoder
    at the target CRF.

    All fields are non-negative floats so the predictor's input
    normalisation is a single per-feature ``(x - mean) / std`` shift.
    """

    # --- probe-encode-derived complexity barometer --------------------
    probe_bitrate_kbps: float  # average bitrate over the probe encode
    probe_i_frame_avg_bytes: float  # mean I-frame size
    probe_p_frame_avg_bytes: float  # mean P-frame size
    probe_b_frame_avg_bytes: float  # mean B-frame size (0 if codec has none)

    # --- optional learned signals (0.0 when unavailable) --------------
    saliency_mean: float = 0.0  # 0..1, from saliency_student_v1 ONNX
    saliency_var: float = 0.0  # variance across the shot's centre frame

    # --- temporal / spatial signals from FFmpeg signalstats -----------
    frame_diff_mean: float = 0.0  # mean abs(frame[t] - frame[t-1])
    y_avg: float = 0.0  # mean luma over the shot
    y_var: float = 0.0  # variance of luma

    # --- structural metadata ------------------------------------------
    shot_length_frames: int = 0
    fps: float = 0.0
    width: int = 0
    height: int = 0


# Resolution classes mirror the ladder.py / corpus.py vocabulary so the
# predictor's input shape is stable across the harness. The integer is
# the predictor's one-hot index.
_RESOLUTION_CLASS: tuple[tuple[int, str], ...] = (
    (480, "sd"),  # ≤ 480 lines
    (720, "hd_ready"),  # 480 < h ≤ 720
    (1080, "hd"),  # 720 < h ≤ 1080
    (2160, "uhd"),  # 1080 < h ≤ 2160
    (4320, "uhd8k"),  # 2160 < h ≤ 4320
)


def resolution_class(height: int) -> str:
    """Return the ladder.py-aligned resolution-class name for ``height``."""
    for limit, name in _RESOLUTION_CLASS:
        if height <= limit:
            return name
    return "uhd8k"  # everything beyond 4320 lumps into the highest class


# Default per-codec analytical-curve coefficients — used when no ONNX
# model is loaded. The form is::
#
#     vmaf ≈ a − b · (crf - crf_ref) − c · (crf - crf_ref)² + d · log(bitrate)
#
# These coefficients are not authoritative; they are seed values that
# produce a monotone, broadly-correct shape so the unit-test path runs
# without an ONNX model. The trained ONNX model replaces them at the
# inference call site.
_DEFAULT_COEFFS: Mapping[str, tuple[float, float, float, float, float]] = {
    # codec        a       b      c        d      crf_ref
    "libx264": (95.0, 1.20, 0.012, 1.5, 23.0),
    "libx265": (96.0, 1.10, 0.010, 1.6, 28.0),
    "libsvtav1": (94.0, 0.95, 0.009, 1.4, 35.0),
    "libaom-av1": (94.0, 0.90, 0.009, 1.4, 35.0),
    "libvvenc": (95.0, 0.85, 0.008, 1.5, 32.0),
    "h264_nvenc": (93.0, 1.30, 0.014, 1.4, 23.0),
    "hevc_nvenc": (94.0, 1.20, 0.012, 1.5, 23.0),
    "av1_nvenc": (93.0, 1.10, 0.011, 1.5, 23.0),
    "h264_amf": (92.0, 1.40, 0.015, 1.3, 23.0),
    "hevc_amf": (93.0, 1.30, 0.013, 1.4, 23.0),
    "av1_amf": (92.0, 1.20, 0.012, 1.4, 23.0),
    "h264_qsv": (93.0, 1.30, 0.013, 1.4, 23.0),
    "hevc_qsv": (94.0, 1.20, 0.012, 1.5, 23.0),
    "av1_qsv": (93.0, 1.10, 0.011, 1.5, 23.0),
}


@dataclasses.dataclass
class Predictor:
    """VMAF predictor — ONNX model + per-codec analytical fallback.

    Construct without arguments to get the analytical fallback (useful
    for tests and dev hosts without onnxruntime). Pass ``model_path``
    pointing at a Sigstore-signed ``predictor_<codec>.onnx`` to enable
    the learned predictor.

    The per-codec coefficients are part of the model card and are
    bumped whenever the ONNX file is retrained.
    """

    model_path: Path | None = None
    coefficients: Mapping[str, tuple[float, float, float, float, float]] = dataclasses.field(
        default_factory=lambda: dict(_DEFAULT_COEFFS)
    )
    _onnx_session: object | None = dataclasses.field(default=None, init=False, repr=False)

    def __post_init__(self) -> None:
        """Lazy-load the ONNX session if a model path is set.

        Falls back silently to the analytical curve when onnxruntime is
        unavailable so the test path doesn't depend on the ML stack.
        Production failures (file present but invalid graph) propagate.
        """
        if self.model_path is None:
            return
        try:
            import onnxruntime as ort  # type: ignore[import-not-found]
        except ImportError:
            self._onnx_session = None
            return
        if not self.model_path.is_file():
            raise FileNotFoundError(
                f"predictor model {self.model_path} does not exist; "
                f"run predictor_train.py to generate it"
            )
        # Pin the CPU provider — the per-shot predictor runs on the same
        # host as the encoder. CUDA / DirectML aren't useful here since
        # the model is tiny (~16 inputs × ~64 hidden × 1 output).
        self._onnx_session = ort.InferenceSession(
            str(self.model_path), providers=["CPUExecutionProvider"]
        )

    def predict_vmaf(
        self,
        features: ShotFeatures,
        target_quality: int,
        codec: str,
    ) -> float:
        """Predict the VMAF score for ``codec`` at ``target_quality``.

        Uses the ONNX model if loaded; falls back to the analytical
        curve. Returns a float clamped to ``[0, 100]``.
        """
        if self._onnx_session is not None:
            return self._predict_onnx(features, target_quality, codec)
        return self._predict_analytical(features, target_quality, codec)

    def _predict_analytical(
        self,
        features: ShotFeatures,
        crf: int,
        codec: str,
    ) -> float:
        """Per-codec analytical fallback. Returns clamped VMAF.

        Form: ``vmaf ≈ a − b·Δ − c·Δ² + d·log(bitrate_kbps)`` where
        ``Δ = crf − crf_ref``. The bitrate term acts as the per-shot
        complexity correction — a high-motion shot's probe encode
        spends more bits at the reference CRF, raising predicted
        quality at the same target CRF.
        """
        a, b, c, d, crf_ref = self.coefficients.get(codec, _DEFAULT_COEFFS["libx264"])
        delta = float(crf) - crf_ref
        # log(0) guard — pin the bitrate floor to a kbps that maps to
        # roughly the lowest probe encode any test fixture produces.
        bitrate_kbps = max(features.probe_bitrate_kbps, 1.0)
        vmaf = a - b * delta - c * delta * delta + d * math.log10(bitrate_kbps)
        return _clamp(vmaf, 0.0, 100.0)

    def _predict_onnx(
        self,
        features: ShotFeatures,
        crf: int,
        codec: str,
    ) -> float:
        """ONNX inference — runs the trained per-codec MLP."""
        # Build the input tensor; layout is documented in the model card.
        # The model is per-codec (no codec one-hot needed) but the
        # session-name dict still keys by the model's input layer name.
        if self._onnx_session is None:  # pragma: no cover — guarded above
            return self._predict_analytical(features, crf, codec)
        import numpy as np  # type: ignore[import-not-found]

        x = np.asarray(
            [
                [
                    float(crf),
                    features.probe_bitrate_kbps,
                    features.probe_i_frame_avg_bytes,
                    features.probe_p_frame_avg_bytes,
                    features.probe_b_frame_avg_bytes,
                    features.saliency_mean,
                    features.saliency_var,
                    features.frame_diff_mean,
                    features.y_avg,
                    features.y_var,
                    float(features.shot_length_frames),
                    features.fps,
                    float(features.width),
                    float(features.height),
                ]
            ],
            dtype=np.float32,
        )
        # Conventional MLP input name; predictor_train.py pins it.
        input_name = self._onnx_session.get_inputs()[0].name  # type: ignore[attr-defined]
        out = self._onnx_session.run(None, {input_name: x})  # type: ignore[attr-defined]
        return _clamp(float(out[0].flatten()[0]), 0.0, 100.0)

    def predict_mos(
        self,
        features: ShotFeatures,
        codec: str,
        *,
        target_quality: int | None = None,
    ) -> float:
        """Predict subjective MOS in ``[1.0, 5.0]`` for ``features``.

        Phase 3 of [ADR-0325 / ADR-0336] — wires the optional
        :mod:`konvid_mos_head_v1` ONNX into the predictor surface.
        When the ONNX is shipped (``model/konvid_mos_head_v1.onnx``)
        and ``onnxruntime`` is available, this loads it and returns
        the head's prediction directly. When the ONNX is missing —
        which is the default until the real-corpus retrain lands —
        we fall back to a documented linear approximation that
        rescales the existing VMAF predictor's output:

        .. math:: \\widehat{\\text{MOS}} = (\\widehat{\\text{VMAF}} - 30) / 14

        The fallback is deliberately conservative: it maps VMAF 30
        (visibly distorted) to MOS 0 and VMAF 100 (transparent) to
        MOS 5, so callers that don't have the MOS head still get a
        plausible 5-point estimate. Per ADR-0325 §Phase 3 the
        fallback is documented as approximate, not authoritative.

        ``target_quality`` is the CRF the caller plans to encode at;
        when ``None`` we pick the codec's default CRF. The MOS head
        itself is encode-agnostic — it consumes the canonical-6
        features + saliency + shot metadata of the *encoded* clip —
        but the fallback path needs a CRF to feed the VMAF predictor.
        """
        head_session = _maybe_load_mos_head()
        if head_session is not None:
            return _predict_mos_via_head(head_session, features)
        # Fallback path. Use the codec's default CRF when none
        # provided so the call site can supply features alone.
        if target_quality is None:
            adapter = get_adapter(codec)
            target_quality = adapter.quality_default
        predicted_vmaf = self.predict_vmaf(features, int(target_quality), codec)
        mos = (predicted_vmaf - 30.0) / 14.0
        return _clamp(mos, 1.0, 5.0)

    def pick_crf(
        self,
        features: ShotFeatures,
        target_vmaf: float,
        codec: str,
    ) -> int:
        """Invert the predictor — binary-search the CRF that hits target.

        Searches the codec adapter's ``quality_range``. The predictor is
        monotone in CRF (verified by unit test), so binary search
        converges in at most ``ceil(log2(range))`` predictor calls.
        """
        return pick_crf(self, features, target_vmaf, codec)

    def pick_keyint(self, features: ShotFeatures, fps: float) -> tuple[int, int]:
        """Pick GOP / min-GOP for a shot using the probe-bitrate heuristic.

        See :func:`pick_keyint`.
        """
        return pick_keyint(features, fps)

    def predict_vmaf_with_uncertainty(
        self,
        features: ShotFeatures,
        target_quality: int,
        codec: str,
        *,
        calibration: object | None = None,
        alpha: float | None = None,
    ) -> tuple[float, float, float]:
        """Predict VMAF and return ``(point, low, high)``.

        Wraps the point estimate from :meth:`predict_vmaf` in a
        conformal prediction interval. ``calibration`` is a
        :class:`vmaftune.conformal.SplitConformalCalibration` or
        :class:`vmaftune.conformal.CVPlusConformalCalibration` instance;
        ``None`` returns ``(point, point, point)`` so the
        ``--with-uncertainty`` flag's degraded path stays well-typed
        when no calibration sidecar ships with the model.

        Coverage guarantee under exchangeability:
        ``P(target in [low, high]) >= 1 - alpha`` per Lei et al. 2018
        Theorem 2.2 (split conformal) and Barber et al. 2021 Theorem 1
        (CV+).
        """
        # Lazy import keeps the conformal module out of the import
        # graph for callers that don't ask for uncertainty.
        from .conformal import ConformalPredictor

        cal = calibration
        if alpha is not None and cal is not None:
            # Honour an explicit alpha override by rebuilding the
            # frozen calibration tuple.
            cal = dataclasses.replace(cal, alpha=alpha)  # type: ignore[arg-type]
        wrapper = ConformalPredictor(base=self, calibration=cal)  # type: ignore[arg-type]
        interval = wrapper.predict(features, target_quality, codec)
        return interval.point, interval.low, interval.high


def pick_crf(
    predictor: Predictor,
    features: ShotFeatures,
    target_vmaf: float,
    codec: str,
) -> int:
    """Find the CRF in the codec's ``quality_range`` that hits ``target_vmaf``.

    Binary search over integer CRFs. The codec adapter's
    ``invert_quality`` field tells us which direction "higher CRF =
    lower quality" runs; the search assumes that contract holds (every
    shipped adapter sets it True today).
    """
    adapter = get_adapter(codec)
    lo, hi = adapter.quality_range
    # Predictor is non-strictly monotone-decreasing in CRF for every
    # shipped codec; binary-search the largest CRF whose predicted VMAF
    # is still ≥ target. That's the most-compressed encode that still
    # meets quality.
    best = adapter.quality_default
    while lo <= hi:
        mid = (lo + hi) // 2
        vmaf = predictor.predict_vmaf(features, mid, codec)
        if vmaf >= target_vmaf:
            best = mid
            lo = mid + 1  # try a higher CRF (more compression)
        else:
            hi = mid - 1
    return best


def pick_keyint(features: ShotFeatures, fps: float) -> tuple[int, int]:
    """Heuristic GOP / min-GOP picker driven by probe bitrate + shot length.

    Returns ``(keyint, min_keyint)``:

    * Long, low-motion shots (probe bitrate below the per-resolution
      median, length above 4 seconds) get an extended keyint of
      ``4 × fps`` — the low motion makes long temporal references
      cheap and improves compression.
    * High-motion shots (probe bitrate above 1.5× the resolution
      median) get a tight ``keyint = fps`` so the encoder can drop
      stale references.
    * Everything else gets the canonical ``keyint = 2 × fps`` /
      ``min_keyint = fps / 2``.

    The "median probe bitrate" thresholds are encoded as constants here
    rather than learned because they need to be human-tunable when an
    operator first runs the predictor on a corpus they care about. The
    learned MLP picks the *CRF* on top of these bands.
    """
    fps_int = max(int(round(fps)), 1)
    # Empirical bands in kbps (probe-encode at the codec's ``probe_quality``)
    # for 1080p natural content. Out-of-resolution content scales linearly
    # in the call site; this default works for anything within ±1 octave.
    low_motion_threshold_kbps = 1500.0
    high_motion_threshold_kbps = 8000.0

    is_long = features.shot_length_frames >= int(round(4.0 * fps_int))
    bitrate = features.probe_bitrate_kbps
    if is_long and bitrate < low_motion_threshold_kbps:
        return (4 * fps_int, fps_int)
    if bitrate > high_motion_threshold_kbps:
        return (fps_int, max(fps_int // 2, 1))
    return (2 * fps_int, max(fps_int // 2, 1))


def make_predictor_predicate(
    predictor: Predictor,
    feature_extractor: Callable[["Shot", str], ShotFeatures],
) -> PredicateFn:
    """Adapt a :class:`Predictor` to the :func:`per_shot.tune_per_shot` seam.

    The ``PredicateFn`` signature is
    ``(shot, target_vmaf, encoder) -> (crf, predicted_vmaf)``. We pull
    the per-shot features from the supplied ``feature_extractor`` (the
    real one lives in ``predictor_features.py`` and probes-encodes the
    shot; tests inject a deterministic stub).
    """

    def _predicate(shot: "Shot", target_vmaf: float, encoder: str) -> tuple[int, float]:
        features = feature_extractor(shot, encoder)
        crf = predictor.pick_crf(features, target_vmaf, encoder)
        vmaf = predictor.predict_vmaf(features, crf, encoder)
        return crf, vmaf

    return _predicate


def _clamp(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


# --- konvid_mos_head_v1 loader (ADR-0325 / ADR-0336 Phase 3) ---------
#
# The MOS head is optional. Most callers will not ship it locally
# until the production-flip gate fires on real KonViD data. The
# loader is module-level (cached after first call) so the per-shot
# loop does not pay an ONNX-session cost per frame.

_MOS_HEAD_CACHE: object | None = None
_MOS_HEAD_RELPATH: Path = Path("model/konvid_mos_head_v1.onnx")


def _resolve_mos_head_path() -> Path | None:
    """Locate ``konvid_mos_head_v1.onnx`` relative to the repo root.

    Walks up from this file until it finds either the model file or
    a directory that *isn't* a parent of the repo root. Returns
    ``None`` when the model isn't shipped — that's the documented
    fallback case.
    """
    here = Path(__file__).resolve()
    for parent in (here, *here.parents):
        candidate = parent / _MOS_HEAD_RELPATH
        if candidate.is_file():
            return candidate
    return None


def _maybe_load_mos_head() -> object | None:
    """Load the MOS head ONNX once; return ``None`` when unavailable.

    Three failure modes — each silently falls back to the linear
    approximation rather than raising, because the predictor must
    keep working on hosts without onnxruntime or the model file:

    1. ``onnxruntime`` not importable -> fallback.
    2. The ONNX file isn't shipped -> fallback.
    3. The session itself raises at construction -> fallback.
    """
    global _MOS_HEAD_CACHE
    if _MOS_HEAD_CACHE is not None:
        # Sentinel object means "we tried already and it failed; don't retry."
        if _MOS_HEAD_CACHE is _MOS_HEAD_FAILED:
            return None
        return _MOS_HEAD_CACHE
    try:
        import onnxruntime as ort  # type: ignore[import-not-found]
    except ImportError:
        _MOS_HEAD_CACHE = _MOS_HEAD_FAILED
        return None
    path = _resolve_mos_head_path()
    if path is None:
        _MOS_HEAD_CACHE = _MOS_HEAD_FAILED
        return None
    try:
        _MOS_HEAD_CACHE = ort.InferenceSession(str(path), providers=["CPUExecutionProvider"])
    except Exception:  # pragma: no cover — defensive for malformed ONNX
        _MOS_HEAD_CACHE = _MOS_HEAD_FAILED
        return None
    return _MOS_HEAD_CACHE


_MOS_HEAD_FAILED = object()  # sentinel — distinguishes "not loaded" from "tried and failed"


def _reset_mos_head_cache_for_tests() -> None:
    """Test seam — clear the cached session so a fresh resolve runs.

    Public consumers don't call this; the test harness does so it
    can exercise both the ONNX-present and the fallback paths
    without an interpreter restart.
    """
    global _MOS_HEAD_CACHE
    _MOS_HEAD_CACHE = None


def _predict_mos_via_head(head_session: object, features: ShotFeatures) -> float:
    """Run the konvid_mos_head_v1 ONNX once and clamp to ``[1, 5]``.

    The MOS head consumes the 11-D feature vector documented in
    :mod:`ai.scripts.train_konvid_mos_head` and the 1-D ENCODER_VOCAB v4
    one-hot (``[1.0]`` — the single ``ugc-mixed`` slot). Defaults to
    zero for the canonical-6 + saliency + shot-metadata fields the
    :class:`ShotFeatures` dataclass does not currently expose; that
    is acceptable because today's call sites are vmaf-tune per-shot
    paths that haven't yet been wired to the canonical-6 extractor —
    they get the head's no-op behaviour and the linear-approximation
    consumers keep working.
    """
    import numpy as np  # type: ignore[import-not-found]

    # Feature vector layout — must match
    # ``train_konvid_mos_head.FEATURE_COLUMNS`` exactly.
    x = np.zeros((1, 11), dtype=np.float32)
    x[0, 6] = float(features.saliency_mean)
    x[0, 7] = float(features.saliency_var)
    # Canonical-6 + shot-metadata default to zero (training corpus
    # mean is non-zero; downstream callers that have these signals
    # available pass them through a richer feature extractor in a
    # follow-up PR).
    encoder = np.ones((1, 1), dtype=np.float32)
    inputs = head_session.get_inputs()  # type: ignore[attr-defined]
    feed: dict[str, object] = {inputs[0].name: x, inputs[1].name: encoder}
    out = head_session.run(None, feed)  # type: ignore[attr-defined]
    return _clamp(float(np.asarray(out[0]).flatten()[0]), 1.0, 5.0)


__all__ = [
    "Predictor",
    "PredicateFn",
    "ShotFeatures",
    "make_predictor_predicate",
    "pick_crf",
    "pick_keyint",
    "resolution_class",
]
