#!/usr/bin/env python3
# Copyright 2026 Lusoris and Claude (Anthropic)
# SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
"""Generate `volk_priv_remap.h` — a force-included header that
prefixes every `vk*` API symbol volk defines with `vmaf_priv_`.

Why: in fully-static link environments (BtbN-style FFmpeg builds
that stitch libvmaf.a + libvulkan.a into one binary), volk's PFN
dispatcher variables and the official Vulkan loader's exported
functions clash on every Vulkan API name. ADR-0185 fixed the
shared-library case via `-Wl,--exclude-libs,ALL`; that flag has
no effect on `ar`-produced static archives. Renaming volk's
copies at the C level removes the clash for both build modes.
See ADR-0198.
"""

import re
import sys

EXPECTED_ARGC = 3  # script-name + volk.h + out.h


def main() -> int:
    if len(sys.argv) != EXPECTED_ARGC:
        sys.stderr.write("usage: gen_priv_remap.py <volk.h> <out.h>\n")
        return 1

    in_path, out_path = sys.argv[1], sys.argv[2]
    with open(in_path, "r", encoding="utf-8") as f:
        volk_h = f.read()

    pattern = re.compile(r"^extern\s+PFN_vk\w+\s+(vk\w+)\s*;", re.MULTILINE)
    syms = sorted(set(pattern.findall(volk_h)))
    if not syms:
        sys.stderr.write(f"gen_priv_remap.py: no `vk*` symbols found in {in_path}\n")
        return 2

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_priv_remap.py — do not edit. */\n")
        f.write("/* Renames volk's `vk*` PFN variables to `vmaf_priv_vk*` so\n")
        f.write(" * libvmaf.a coexists with a consumer's libvulkan.a in\n")
        f.write(" * fully-static link environments (BtbN-style FFmpeg).\n")
        f.write(" * Force-included into volk.c and every libvmaf TU that\n")
        f.write(" * links against volk_dep. See ADR-0198. */\n")
        f.write("#ifndef VMAF_VOLK_PRIV_REMAP_H_\n")
        f.write("#define VMAF_VOLK_PRIV_REMAP_H_\n\n")
        for s in syms:
            f.write(f"#define {s} vmaf_priv_{s}\n")
        f.write("\n#endif /* VMAF_VOLK_PRIV_REMAP_H_ */\n")

    sys.stdout.write(f"gen_priv_remap.py: wrote {len(syms)} renames to {out_path}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
