/**
 *  Copyright 2026 Lusoris and Claude (Anthropic)
 *  SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
 *
 *  CUDA host glue header for the CAMBI banding-detection feature extractor
 *  (T3-15 / ADR-0360). Strategy II hybrid — GPU kernels for spatial mask,
 *  decimate, and filter_mode; host CPU for calculate_c_values + topk pooling.
 */
#ifndef FEATURE_CAMBI_CUDA_H_
#define FEATURE_CAMBI_CUDA_H_

#include <stdint.h>
#include "common.h"

/* PTX blob generated by nvcc from integer_cambi/cambi_score.cu. */
extern const unsigned char cambi_score_ptx[];

#endif /* FEATURE_CAMBI_CUDA_H_ */
