/**
 *  Copyright 2026 Lusoris and Claude (Anthropic)
 *  SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
 */

#ifndef LIBVMAF_VULKAN_COMMON_H_
#define LIBVMAF_VULKAN_COMMON_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Generated by /add-gpu-backend vulkan. Replace the stubs in this file,
 * picture_vulkan.c, and feature/vulkan/<feature>_vulkan.c with real
 * implementations.
 */

typedef struct VmafVulkanContext VmafVulkanContext;

int vmaf_vulkan_context_new(VmafVulkanContext **ctx, int device_index);
void vmaf_vulkan_context_destroy(VmafVulkanContext *ctx);
int vmaf_vulkan_device_count(void);

#ifdef __cplusplus
}
#endif

#endif /* LIBVMAF_VULKAN_COMMON_H_ */
