/**
 *  Copyright 2026 Lusoris and Claude (Anthropic)
 *  SPDX-License-Identifier: BSD-3-Clause-Plus-Patent
 *
 *  Picture allocation / lifecycle for the Vulkan backend.
 *  Generated by /add-gpu-backend vulkan as a stub — replace with a real
 *  VkBuffer / VkImage allocator backed by VMA when the kernels need it.
 *  See ADR-0175 + ADR-0127 for the rollout plan.
 */

#include <errno.h>
#include <stddef.h>

#include "picture_vulkan.h"

int vmaf_vulkan_picture_alloc(VmafVulkanContext *ctx, void **out, size_t size)
{
    (void)ctx;
    (void)out;
    (void)size;
    /* TODO: allocate a VkBuffer + VkDeviceMemory pair via VMA. */
    return -ENOSYS;
}

void vmaf_vulkan_picture_free(VmafVulkanContext *ctx, void *buf)
{
    (void)ctx;
    (void)buf;
    /* TODO: vmaDestroyBuffer / vkFreeMemory. */
}
