#!/usr/bin/env python3
"""Generate the 1024-entry sRGB EOTF LUT committed at
libvmaf/src/feature/ssimulacra2_eotf_lut.h.

Ensures deterministic ssimulacra2 output across hosts: libm powf
varies by ~1 ulp between glibc/musl/macOS libSystem, which compounded
to ~2e-4 per-frame drift in the pooled score. Committing the LUT as
hardcoded float bit patterns removes the runtime libm dependency.
"""

import struct

N = 1024

# sRGB EOTF piecewise threshold per IEC 61966-2-1.
SRGB_PIECEWISE_THRESHOLD = 0.04045

print("/**")
print(" *")
print(" *  Copyright 2026 Lusoris and Claude (Anthropic)")
print(" *")
print(' *     Licensed under the BSD+Patent License (the "License");')
print(" *")
print(" */")
print("")
print("/* AUTO-GENERATED by scripts/gen_ssimulacra2_eotf_lut.py.")
print(" * Do not edit by hand — re-run the generator. */")
print("")
print("#ifndef SSIMULACRA2_EOTF_LUT_H_")
print("#define SSIMULACRA2_EOTF_LUT_H_")
print("")
print("#include <stdint.h>")
print("")
print(f"#define SS2_EOTF_LUT_SIZE {N}")
print("")
print("/* LUT[i] = srgb_eotf(i / (SS2_EOTF_LUT_SIZE - 1)) for i in [0, N-1],")
print(" * where srgb_eotf(v) = v/12.92 if v<=0.04045 else ((v+0.055)/1.055)^2.4. */")
print("static const float vmaf_ss2_eotf_lut[SS2_EOTF_LUT_SIZE] = {")

for i in range(N):
    x = i / (N - 1)
    v = x / 12.92 if x <= SRGB_PIECEWISE_THRESHOLD else ((x + 0.055) / 1.055) ** 2.4
    # Round to float32 explicitly and commit as hex-float literal (exact bit pattern).
    f32 = struct.unpack("<f", struct.pack("<f", v))[0]
    # Python supports hex-float literals via .hex(), C99 supports 0x1.bp-3f etc.
    hex_lit = float.hex(f32)
    # Strip trailing 'f' if present (Python uses 64-bit hex internally, but round-trip f32 is exact).
    print(f"    {hex_lit}f,   /* x={x:.6f}, v={f32:.8e} */")

print("};")
print("")
print("#endif /* SSIMULACRA2_EOTF_LUT_H_ */")
